version: '3'
services:
  kafka-landoop:
    image: landoop/fast-data-dev
    ports:
      - 2181:2181
      - 3030:3030
      - 8081:8081
      - 8082:8082
      - 8083:8083
      - 9092:9092
    environment:
      ADV_HOST: 127.0.0.1
